---
- name: Create group {{ airsonic_group }}
  group:
    name: '{{ airsonic_group }}'

- name: Create user {{ airsonic_user }}
  user:
    name: '{{ airsonic_user }}'
    group: '{{ airsonic_group }}'
    create_home: 'no'

- name: Create Airsonic directory
  file:
    path: '{{ airsonic_dir }}'
    owner: '{{ airsonic_user }}'
    group: '{{ airsonic_group }}'
    mode: '0755'
    state: directory

- name: Download Airsonic war 10.6.2
  get_url:
    url: https://github.com/airsonic-advanced/airsonic-advanced/releases/download/11.0.0-SNAPSHOT.20201007202626/airsonic.war
    dest: '{{ airsonic_dir }}'
    owner: '{{ airsonic_user }}'
    group: '{{ airsonic_group }}'
    mode: '0644'
    force: 'no'
  notify: reload service

- name: Download systemd service
  get_url:
    url: https://raw.githubusercontent.com/airsonic-advanced/airsonic-advanced/master/contrib/airsonic.service
    dest: '{{ airsonic_service_path }}/{{ airsonic_service_name }}'
    force: 'no'
  notify: reload service

- name: Systemd remove Context-Path from command line
  lineinfile:
    path: '{{ airsonic_service_path }}/{{ airsonic_service_name }}'
    regexp: 'Dserver.servlet.context-path'
    state: absent
  notify: reload service

- name: Systemd remove Context-Path from environnement
  lineinfile:
    path: '{{ airsonic_service_path }}/{{ airsonic_service_name }}'
    regexp: 'CONTEXT_PATH='
    state: absent
  notify: reload service

- name: Download systemd-env
  get_url:
    url: https://raw.githubusercontent.com/airsonic-advanced/airsonic-advanced/master/contrib/airsonic-systemd-env
    dest: '{{ airsonic_systemd_env }}/airsonic'
    force: 'no'
  notify: reload service

- name: Install ffmpeg
  apt:
    name: ffmpeg
    state: present

- name: Create transcoder directory
  file:
    path: '{{ airsonic_dir }}/transcode'
    owner: '{{ airsonic_user }}'
    group: '{{ airsonic_group }}'
    mode: '0755'
    state: directory

- name: Make ffmpeg the default transcoder
  file:
    src: /usr/bin/ffmpeg
    path: '{{ airsonic_dir }}/transcode/ffmpeg'
    state: link
  notify: reload service
